version: '3.8'

services:
  jupyter:
    build: .
    container_name: vpp-cfla-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    env_file: 
      - path: ./.env

