version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: web-backend
    ports:
      - "8080:8080" # conatiner: host
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  frontend:
    image: nginx:alpine
    container_name: web-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
