FROM python:3.12-slim

WORKDIR /app
# Copy all file from backend dir into container
COPY . . 
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install python-multipart

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
